### ISSUE TITLE
Incompatible with Ratpack

### ISSUE THREAD

**Issue by garadox** [jaegertracing/jaeger-client-java#250]
Due to the nature of Ratpack's ExecutorService and not being able to inject / override it with the wrapper, this library appears to be incompatible.

I'm not an expert on Ratpack, so please tell me i'm wrong - I would very much like to use this client library. Maybe an implementation of ActiveSpanSource using a registry, or something else that's not ThreadLocal would work?

**Comment by black-adder** [comment]
Disclaimer: I have no idea what Ratpack is.

Ok, so looking through the Ratpack issues, I saw this: https://github.com/ratpack/ratpack/issues/913 which looks like someone has gone and added zipkin support for Ratpack. Unless we can get someone to instrument Ratpack with opentracing, I'd suggest using https://github.com/hyleung/ratpack-zipkin since Jaeger can accept zipkin spans in the backend.

**Comment by garadox** [comment]
Thanks, i'll check out the instrument repo for Ratpack. Closing this for now.
