### ISSUE TITLE
Adaptive header codec selection

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-client-java#294]
Currently the developer needs to choose which codec they will use for handling headers for a `Tracer` - either the default which uses Jaeger's headers or the B3 codec.

This means that the headers used for inbound/outbound requests need to conform to one or the other strategy - and that therefore assumes the services being communicated with will also adopt the same strategy.

Wondering if it would be better to use an adaptive approach? For example,

* If the inbound request only has Jaeger headers, then any outbound requests from that service will also just use Jaeger headers (by default), unless a config property indicates B3 should also be applied
* If the inbound request includes B3 headers, then the outbound requests will use both Jaeger and B3 headers.

Baggage can be dealt with separately - regardless of whether B3 headers are used on inbound/outbound requests.

**Comment by yurishkuro** [comment]
not too difficult to support, but I wonder how much value is in that approach. It seems that at minimum you would always want to include both sets of headers for the outbound requests, since it's hard to predict in which chain of services a given service is being called, e.g. A(j) -> B(j,z) -> C(j), D(z) -> B(j,z) -> C(j) - the second chain is broken.

**Comment by objectiser** [comment]
I was trying to find a way to avoid adding B3 headers on outbound requests, unless either they were present on the inbound, or the service had been explicitly configured/instructed to add them.

Not sure I understand your example - if reading correctly, the service D sends request to B with B3 headers, then B sends a request to C with both Jaeger and B3, and C receives the request but is only interested in the Jaeger headers? or am I reading it incorrectly?

**Comment by yurishkuro** [comment]
the gist of my example is that you have a heterogeneous mix of services where some propagate B3 while others propagate Jaeger, and yet others do both, which is what this issue seems to be about. If services that can do both are adaptive to the inbound format, it still may break downstream services that can only handle one format, because depending on the shape of the call graph the adaptive service may need to send Z or J to the same downstream svc. That's why I'm saying that adaptive doesn't really work, except for some special cases where the call graph has certain restrictions. For more general call graphs the adaptive services should not be adaptive but rather sending out both formats.

**Comment by yurishkuro** [comment]
Incidentally, sending both formats is easier to implement, no changes required to in-memory context.

I would also prefer this kind of implementation to happen when `Trace-Context` header is finalized.

**Comment by objectiser** [comment]
Sending both is fine with me - just wasn't sure that you would want all the headers sent in an environment where all services may only need just the Jaeger header.

> I would also prefer this kind of implementation to happen when Trace-Context header is finalized.

Do you mean don't do any change now and wait for `Trace-Context`?

Or do you mean do the change now for B3, and then apply the same approach for `Trace-Context` when available?

Reason for creating the issue is that when running an instrumented service in Istio, it would need the B3 codec. Currently this would require code change in the service to install the B3 codec. Would prefer if this could be handled automatically. Other option would be to provide Configuration option to install the B3 codec.

**Comment by yurishkuro** [comment]
I'd certainly prefer not to have B3 codec by default.  conf option is fine. 

Yes I meant not to implement it now until trace-context is available. But that's subject to needs.

Not sure I follow the issue with istio. Envoy uses binary encoding and its own header as one of the options. It also allows tracer-native headers. Are you saying B3 is required by istio? Even more reason to emphasise trace-context.

**Comment by objectiser** [comment]
Agree trace-context would be the ideal solution, with pluggable tracer in the proxy and istio mixer. But currently istio only configures the zipkin tracer and therefore any in-service tracing would have to use the B3 propagation format.
