### ISSUE TITLE
Make tracer & span constructors protected

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#508]
We're trying to migrate away from the legacy client with `com.uber.jaeger` classes, but there is a lot of code internally that still refers to those, and it would be a lot simpler if we could subclass tracer and span, which requires (a) making constructors protected, and (b) potentially minor refactoring to move calls to constructors into virtual functions that can be overridden.

cc @isaachier

**Comment by isaachier** [comment]
I'm wondering if we can just force people to refactor when they upgrade. If we make this internal client a breaking change, it would be easier to just override the config for internal use cases and allow people to use an IDE to fix Jaeger compatibility. Otherwise, not sure there is any impetus for them to ever migrate to new API.

**Comment by yurishkuro** [comment]
You can hardly force people to do anything. Increasing friction of the upgrade will only lead to people not upgrading. For example, if they have `com.uber.jaeger.Tracer tracer = config.build()`, it is a lot easier if we simply keep returning this class (even if its API is slightly different). There might be breaking changes to some people, e.g. if they are calling getTraceId() on JaegerSpanContext, but for most people upgrade will be non-event if we keep the same com.uber.* class names.

**Comment by isaachier** [comment]
OK I get that, but then what is the argument for them to stop using `TracingUtils` when they clearly use it all over the place? Won't they have the same reaction?

**Comment by yurishkuro** [comment]
We can deprecated that API. It already has issues with being dependent on GlobalTracer, which forces people to make a Set() call at the beginning.

**Comment by isaachier** [comment]
Right I guess I see that. In general, I guess it is a balance of what you can do before you aggravate people so much that they are unwilling to upgrade.

**Comment by pavolloffay** [comment]
>  if we could subclass tracer and span, 

The subclass will reference symbols from the parent e.g. If you subclass `TracerBuilder` it will require `io.jaegertracing` objects. 

I would be interested to see a PR in https://github.com/jaegertracing/legacy-client-java using snapshot of  #509 before merging it.

**Comment by isaachier** [comment]
Ya you definitely do add a dependency on `io.jaegertracing`. The plan isn't to merge this into the legacy client because it would not change anything. Instead, we would release a new version of the legacy client (at least internally at Uber) that would subclass certain key classes, but otherwise be empty. The users would not have to do anything other than upgrade to the latest legacy client. The dependency on `io.jaegertracing` would be included transitively. The API should remain almost identical to what the legacy client users are used to.

**Comment by pavolloffay** [comment]
Adding a dependency to `io.jaegertracing` is obvious I am talking about something a little bit different...

But I am not sure if subclassing `io.jaegertacing` in legacy client is enough. The subclass still references symbols from `io.jaegertracing` which causes breaking change anyways.  I would like to see a PR to legacy client showing  #509 allows you to do it. 

> , we would release a new version of the legacy client (at least internally at Uber) that would subclass certain key classes, but otherwise be empty. The users would not have to do anything other than upgrade to the latest legacy client. 

It could be helpful also in the community.

**Comment by isaachier** [comment]
Sure I can try using a snapshot with #509 before merging, and I'll publish PR to legacy client.
