### ISSUE TITLE
SenderException should be logged in debug or trace to help debugging connectivity issues

### ISSUE THREAD

**Issue by ghilainm** [jaegertracing/jaeger-client-java#606]
I have recently deployed jaeger UI and I am using jaeger-client, they are no logs in the code which allows to debug connectivity issues. 

The following line should be changed to add logging of exception 
https://github.com/jaegertracing/jaeger-client-java/blob/bb0fa210e1578c6a53fea611181538527ead3874/jaeger-core/src/main/java/io/jaegertracing/internal/reporters/RemoteReporter.java#L106

**Comment by objectiser** [comment]
The location you reference is in the close method, so the one I think you mean is https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/reporters/RemoteReporter.java#L178 ?

Even if trace logging, it could result in a large number of log entries. If the purpose is to debug initial (or intermittent) connectivity issues, possibly would be good to have a mechanism that only reported the first exception of a group.

Would you be interested in submitting a PR?

**Comment by claudio4j** [comment]
It happened to me recently, where I had wrongly set the URl for the JAEGER_ENDPOINT environment variable, the result was the traces were not reported, later I found out the JAEGER_ENDPOINT was the 'query' endpoint instead of the 'collector' endpoint, but I found it just after debugging the source code and a couple of hours. The response from the endpoint was "405 Method Not Allowed" and a non null empty response body.
So, a WARN/ERROR would help a lot to early spot the problem.

I will propose a fix to log the first exception as @objectiser suggests.
