### ISSUE TITLE
Release 0.35.0 based on OpenTracing 0.32.0

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#614]
Master now contains an upgrade to OpenTracing 0.32.0. Is there anything blocking the release or can we release?

**Comment by yurishkuro** [comment]
+1  to release

**Comment by pavolloffay** [comment]
@yurishkuro would you have time to look at https://github.com/jaegertracing/jaeger-client-java/pull/609? I will cut the release early next week.

**Comment by pavolloffay** [comment]
I am going to cut it now

**Comment by pavolloffay** [comment]
The artifact has been published https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-core/0.35.0/

**Comment by Fox32** [comment]
@pavolloffay  I just noticed that it is also required to upgrade [`java-tracerresolver`](https://github.com/jaegertracing/jaeger-client-java/blob/master/build.gradle) to version [0.1.6](https://github.com/opentracing-contrib/java-tracerresolver/releases), otherwise there is still a dependency to 0.31.0 of OpenTracing.
