### ISSUE TITLE
Update libthrift to 0.13.0

### ISSUE THREAD

**Issue by MrBerg** [jaegertracing/jaeger-client-java#669]
## Requirement - what kind of business use case are you trying to solve?

Apache Thrift up to and including version 0.12.0 is vulnerable to [CVE-2019-0205](https://nvd.nist.gov/vuln/detail/CVE-2019-0205) (and [CVE-2019-0210]( https://nvd.nist.gov/vuln/detail/CVE-2019-0210) but that is probably not relevant here)

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Once https://github.com/ahawkins/docker-thrift/pull/22 has been merged it should be pretty easy to bump the thrift version (though there might of course be [breaking changes](https://github.com/apache/thrift/blob/0.13.0/CHANGES.md#breaking-changes)).

## Any open questions to address

It might also (maybe even probably) be the case that jaeger isn't vulnerable to this and the update isn't needed. In that case it should be enough to have that documented somewhere.

**Comment by yurishkuro** [comment]
Jaeger in general does not use thrift RPC components, only the encoding. It looks like the first cve should not affect this lib.

**Comment by loicmathieu** [comment]
@yurishkuro even if Jaeger is not affected, this is an issue for those how use dependency analysis tools (like OWASP dependency check) because these tools we display an error for this library.

The same error will exist for people making security audit as the auditer will not analyse the use of the library inside the application (and all it's dependency) but just advise to update te version of a vulnerable library.

So please, can you update to libthrift 0.13 ?
