### ISSUE TITLE
Service name must not be null or empty

### ISSUE THREAD

**Issue by ahmedbaberkhan** [jaegertracing/jaeger-client-java#683]
## Requirement - what kind of business use case are you trying to solve?

I want to disable jaeger span using 
   opentracing-jaeger-enabled: false and no jaeger service name is defined.

## Problem - what in Jaeger blocks you from solving the requirement?

java.lang.IllegalArgumentException: Service name must not be null or empty

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The service name should be check if and only if the enabled flag is set to true.

**Comment by objectiser** [comment]
I'm guessing that you are using https://github.com/opentracing-contrib/java-spring-jaeger ?

You need to create an issue in the project that defines that property, so that if disabled, it should return the `NoopTracer` instead of `JaegerTracer`.

Closing the issue - feel free to reopen if needs further discussion.

**Comment by ahmedbaberkhan** [comment]
Thanks
