### ISSUE TITLE
Add trace IDs into std logging (MDC)

### ISSUE THREAD

**Issue by seho-kim-do-something** [jaegertracing/jaeger-client-java#715]
Hi,
I am new to Jaeger, and need some help on how to make span reported with logs.
With logback, I see spans with logs including application logs from the UI, but with log4j2 it doesn't get any log messages.
Is there any way to work with log4j2?
Thanks,
Seho

**Comment by pavolloffay** [comment]
Hi @seho-kim-do-something, thanks for reporting the issue.

MDC OpenTracing implementation (putting trace IDs into logs) requires wrapping of `ScopeManager`. The scope manger is configured at tracer creation time which is vendor specific operation. Hence this integration is specific per vendor. We could implement the MDC integration directly in this repository since the `jaeger-core` depends on SLF4j anyway.

http://www.slf4j.org/api/org/slf4j/MDC.html
https://github.com/quarkusio/quarkus/blob/master/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/MDCScopeManager.java

**Comment by seho-kim-do-something** [comment]
Thank you @pavolloffay

**Comment by winster** [comment]
Hi,

I have a springboot-webflux application and I was expecting traceID in the slf4j logs. But I don't see it. Below is my dependencies
```
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>3.1.2</version>
        </dependency>
        <dependency>
            <groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-client</artifactId>
            <version>1.3.2</version>
        </dependency>
```
I used 1.3.2 seeing that this PR was merged on Jun 27.

**Comment by yurishkuro** [comment]
Just dependency is not sufficient, see https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core#log-correlation
