### ISSUE TITLE
Is it possible to query traces from Java tool?

### ISSUE THREAD

**Issue by remal** [jaegertracing/jaeger-client-java#717]
Hello,

I'm writing a Java tool that should request traces with spans from Jaeger and do some logic.

[Trace retrieval APIs](https://www.jaegertracing.io/docs/1.16/apis/#trace-retrieval-apis) documentation page says that there is stable gRPC interface. However I couldn't find a Java library that can query traces from Jaeger.

I've also tried to compile [query.proto](https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/query.proto) file myself (from Gradle script) and it's quite hard to implement all protobuf compiler tweaks that you use (precreated Docker image with a lot of params).

Is there such querying traces Java library? If not, are there any plans to create it?

**Comment by yurishkuro** [comment]
Did you try using https://github.com/jaegertracing/docker-protobuf ?

**Comment by remal** [comment]
@yurishkuro No, I didn't. First of all, because it requires me to throw out existing protobuf Gradle plugin(s). And I still need to pass a lot of parameters: https://github.com/jaegertracing/jaeger-idl/blob/master/Makefile. Moreover, I couldn't find any documentation, so I supposed that troubleshooting could take a lot of time.

Unfortunately right now I see only one solution: rely on unstable JSON API and pray that everything works fine and will work fine when we decide to upgrade Jaeger. Or to convince the team to move to another solution with stable JSON API like Zipkin.

If you already create some gRPC from these files, please start publishing query API.

BTW it's also not so clear are current proto files compatible with previous Jaeger version or not. If I managed to build query API, with what Jaeger versions could it work?

**Comment by yurishkuro** [comment]
We do not plan to publish/maintain auto-generated code, the Proto definitions *are* the API.

The [Makefile][] in jaeger-idl uses the Docker image to generate code for all languages as part of the CI.

Gradle plugin can be made to work with a Docker image too, we do it in this repo to generate the Thrift files:
  * https://github.com/jaegertracing/jaeger-client-java/blob/0d4c67566644b2335006fe7e234a8f28add90ef4/jaeger-thrift/build.gradle#L24-L30
  * https://github.com/jaegertracing/jaeger-client-java/blob/master/travis/docker-thrift/thrift

The Jaeger backend is almost always on the latest version of the IDL files. The exact revisions can be checked from the submodules, I just added an explanation to [jaeger-idl/README](https://github.com/jaegertracing/jaeger-idl/blob/master/README.md).

[Makefile]: https://github.com/jaegertracing/jaeger-idl/blob/master/Makefile#L46

**Comment by remal** [comment]
Please correct me if I'm wrong, but if I understand correctly, you publish a java client for span reporting API. Isn't part of it generated? Would it be so difficult to publish another client of another API? By "publish" I mean publishing to MavenCentral/JCenter.

If I manage to generate Java code from current proto file, will it support previous version of Jaeger Query service? And what about future versions?

**Comment by yurishkuro** [comment]
This repository is the SDK that implements the OpenTracing API. Yes, it uses generated code as part of the library, but that code is not exposed to the users of the library, they are only exposed to the explicitly defined public API, which is OpenTracing.

Generating code for consuming gRPC service is the normal course of action of interacting with such services. Unless someone wants to expose a specific _business API_ on top of the auto-generated classes, there's little value in publishing artifacts with only generated code. In fact, there are significant downsides to doing that because it creates a dependency hell by depending on specific versions of the frameworks (e.g. generated code may be significantly different even between minor versions of the generator plugin).

Your questions about compatibility are orthogonal to the discussion about publishing gen-code artifacts - if the Protobuf schema of the services changes in incompatible ways, the client library might break regardless of who generated the code, because gen-code and protobuf definitions are coupled in a 1-1 relationship.

**Comment by remal** [comment]
What should I do if you decide to change the way you build your proto file? I don't use Makefile, so I have to write all the logic myself, right? In this case if you change Makefile, most probably I get some not obvious issues. Can you suggest something here?

**Comment by yurishkuro** [comment]
Sorry, I don't understand what difficulties you're expecting. If you look at _virtually any gRPC tutorial_, they all start with showing how to generate client classes from proto files. That's just a fact of life, this is how you consume gRPC/Proto services.

Since our proto files include certain non-standard annotations, we provided a Docker image as an alternative to off-the-shelf `protoc` compiler that includes the additional dependencies.

**Comment by remal** [comment]
OK, I got your points. I'll try to generate Java sources. But I would appreciate it if you start providing some Java client for Query API. How about adding it to some "possible improvements list" and see if people need it or not? I believe I saw one more issue about this topic.

**Comment by remal** [comment]
OK, I got your points. I'll try to generate Java sources. But I would appreciate it if you start providing some Java client for Query API. How about adding it to some "possible improvements list" and see if people need it or not? I believe I saw one more issue about this topic.

**Comment by yurishkuro** [comment]
Don't recall much demand for such library yet, but it's certainly possible. Feel free to start a project like that, if you're willing to maintain it. We can provide links to such projects in some central location, like https://www.jaegertracing.io/docs/1.18/apis/.

The question of API versioning is something we'll need to address indeed, right now we don't have any https://github.com/jaegertracing/jaeger-idl/releases.
