### ISSUE TITLE
The new function Jaeger-client supports writing Span data directly to Kafka

### ISSUE THREAD

**Issue by xuanvinhln** [jaegertracing/jaeger-client-java#759]
Hi Jaeger team,

## Requirement:
**Use case:** In this architecture https://www.jaegertracing.io/img/architecture-v2.png.
When I don't want to use Agent and Collector to save CPU and RAM resources (because I am not using the Sampling function). I think the Jaeger-client should support sending data directly to Kafka.

## Problem
- When the user does not use the Sampling function, the two modules Agent and Collector almost only forwards data, which consumes CPU, RAM, and Network throughput resources.

## Proposal
- The Jaeger Client can be configured to bypass the Agent and Collector, sending spans directly to the Kafka.

Thanks for your support!

**Comment by yurishkuro** [comment]
If someone wants to implement this, here are some tips:
  * it should be a separate module/artifact that users can optionally include
  * the functionality can be implemented as either a full Reporter or as a Sender (used with RemoteReporter). The advantage of the latter is the Reporter can provide queueing & background thread to submit the spans to Kafka.
  * the new component should accept an Encoder that would convert spans to bytes, so that different encodings could be plugged in (proto, thrift, JSON, etc.)

**Comment by jabolina** [comment]
Did anyone started working on this? I would like to try.

@yurishkuro Thanks for the comment, I'll look around and try to start. This module should be similar as the `jaeger-zipkin` module?
