### ISSUE TITLE
Shade kotlin runtime in shadow jar

### ISSUE THREAD

**Issue by ohadgur** [jaegertracing/jaeger-client-java#797]
Currently, the "shadow" jar (of jaeger-thrift) contains some unshaded libraries - mainly kotlin runtime (coming from OkHttp), which causes runtime errors when using a different version of kotlin.
There are other libraries that probably should be excluded from the upber-jar (or shaded if needed), e.g javax, opentracing, intellij annotations.

**Comment by ohadgur** [comment]
@yurishkuro first, sorry for commenting on this close issue. 
when is a new version supposed to be released? since the current shadow jar is problematic

**Comment by yurishkuro** [comment]
@albertteoh how did you do the release the last time?  The travis build is gone, and our release instructions are not updated.

**Comment by albertteoh** [comment]
@yurishkuro actually, I didn't successfully do the release last time due to what appears to be the same reasons you mentioned.

@jpkrohling helped to complete the release and [here's the relevant slack chat thread](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1617006296070000?thread_ts=1615881074.000400&cid=CGG7NFUJ3) that discusses the problems faced and what steps were taken to perform the manual release and I think the key part was:

> I ran the commands from the travis config plus the deploy.sh

It would be good to complete #765 to get us over the current state of limbo. I've pinged the author of #766 to see if there's a chance of making more progress.

**Comment by ohadgur** [comment]
@yurishkuro @albertteoh any updates on the release?
