### ISSUE TITLE
Allow for easy logging of traceIds

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#86]
Most applications don't have a formal way of correlating log lines for a given request even within the application. 
For these applications, it would be very beneficial to set the traceId in a [MDC](http://www.slf4j.org/api/org/slf4j/MDC.html) which allows end users to simply add the traceId's MDC parameter to their log format string, enabling them to separate log lines on a per request basis.

**Comment by yurishkuro** [comment]
I am not in favor of this. Imaging that your service has created a number of different spans while executing a single request. With the proposal about the logs will be tagged with the trace ID without any correlation to the currently active span. So we're upfront making it easier for people to collect lesser quality data. I have published an internal document ys-27 that provides a better solution.

**Comment by awhiteside** [comment]
link to ys-27 ?

**Comment by yurishkuro** [comment]
it's an internal doc, ping jaeger mail group.

**Comment by vprithvi** [comment]
@yurishkuro I agree that what you propose in ys-27 is ideal, but I think this allows users to use tracing with their existing logging infrastructure. Instead of having just the traceId, we could have  a traceId:spanId tuple.

**Comment by adriancole** [comment]
Is there any way to make this discussion less abstract? Ex summarize ys-27
somehow?

**Comment by ccl0326** [comment]
Hi gays, so what's the really plan for correlating log?  We really need this feature.
@yurishkuro can the internal doc be shared?
Now if i want to implement this feature like brave i should replace TracingUtils and get spanId and traceId in hack way.

**Comment by yurishkuro** [comment]
the doc in question only deals with Go API. The gist of that solution is implemented in the HotROD demo's logging: https://github.com/uber/jaeger/tree/master/examples/hotrod/pkg/log

In Java things are a bit simpler. The recent opentracing API change introduced an ActiveSpanSource concept for in-process propagation that allows retrieving the currently active span for any thread (in jaeger-context module TraceContext util was performing a similar role, but it will be deprecated in favor of the "active span source"). So to get the current trace/span IDs into the logs there are two options:
  * use some sort of custom formatter or interceptor in the logging framework that extracts the IDs and adds them to the log message
  * use a custom implementation of ActiveSpanSource that not only stores the span in TLS, but also manages the MDC.

In either case, you would have to cast the `opentracing.Span` to Jaeger Span in order to access trace/span IDs, since those currently are not a part of OpenTracing API (it might change it the github.com/tracecontext proposal gains traction).

**Comment by ccl0326** [comment]
@yurishkuro Thanks your quick reply.I will try this as your thought.

**Comment by ccl0326** [comment]
@yurishkuro I have been implemented it as your thought. But now i think we should trace log without sample, Only sample when send span. Can jaeger agent support this?

**Comment by yurishkuro** [comment]
can you elaborate?

**Comment by ccl0326** [comment]
@yurishkuro We want every logs have trace and span id, so we don't want to tracing with any sampling. if we can sampling when span is sending, this can reduce pressure for storage layer.

**Comment by yurishkuro** [comment]
Tracing is always on for 100% of requests as far as trace/span ID generation and propagation is concerned. It's not subject to sampling. However, if the span is not sampled, it will not be recording tags and logs, and the rest of the data in the span will be dropped once it is finished.

That means that you can always have trace/span ID when writing log statements, but you won't be able to retrieve those traces from storage if they happened to be not sampled.

**Comment by jpkrohling** [comment]
Could this one be closed? Trace IDs are becoming a standard for OpenTracing and a such a feature would probably belong to an instrumentation at `opentracing-contrib`.

I'm closing this, but feel free to reopen if you feel differently.
